"""Add messages

Revision ID: 95adabbfb9ec
Revises: 6059a5dba1d1
Create Date: 2024-03-14 02:23:49.110295

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '95adabbfb9ec'
down_revision = '6059a5dba1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
